load(":cpp_modules_test.bzl", "cpp_modules_tests")

cpp_modules_tests(
    name = "cpp_modules_tests",
    test_kwargs = {
        "attr_values": {
            "tags": [
                "manual",
                "notap",
            ],
        },
    },
)
